empty_alt_ignore: true
url_ignore:
  - "https://github.com/kay-a11y/aftermark/blob/main/lsb/entro_checker.py"
  - "https://github.com/kay-a11y/aftermark/blob/main/lsb/bit_planes.py"
  - "https://github.com/kay-a11y/aftermark/blob/main/jpg/jpeg_gonewild.py"